Repository DeveloperAcademy-POSTECH/MacC-Dime-Flicker, pull requests merged in 2022-11, with the labels that each got.

#4 💄 유저가 작가의 세부정보를 볼 수 있는 뷰의 UI를 구현했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Resource/Assets.xcassets/port1.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port1.imageset/IMG_8377.jpg
  Flicker/Global/Resource/Assets.xcassets/port2.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port2.imageset/IMG_8378.jpg
  Flicker/Global/Resource/Assets.xcassets/port3.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port3.imageset/IMG_8379.jpg
  Flicker/Global/Resource/Assets.xcassets/port4.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port4.imageset/IMG_8380.jpg
  Flicker/Global/Resource/Assets.xcassets/장루키.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/장루키.imageset/장루키.jpeg
  Flicker/Network/APIResponseDTO.swift
  Flicker/Network/AccessKey.swift
  Flicker/Network/NetworkErrorCase.swift
  Flicker/Network/NetworkManager.swift
  Flicker/Screens/Artist/ArtistPortfolioCell.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: feature, 루키

#10 Merge시 pbxfile 충돌방지를 위해 gitattribute를 추가합니다.
  .gitattributes
Labels: documentation, 루키

#12 ✨ 애플로그인을 파이어베이스 연동으로 변경했습니다 & 💄LoginViewController의 UI를 구현했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UIColor+Extension.swift
  Flicker/Global/Extensions/UIFont+Extension.swift
  Flicker/Global/Resource/TsukimiRounded-Bold.ttf
  Flicker/Global/Supports/AppDelegate.swift
  Flicker/Global/Supports/Info.plist
  Flicker/Screens/Login/KeychainItem.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/SignUp/ProfileSettingViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
Labels: feature, 하디

#14 :lipstick: AccountDeleteView UI 완성
  .gitattributes
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UIColor+Extension.swift
  Flicker/Screens/Profile/AccountDeleteViewController.swift
Labels: feature, 켄

#17 💄 MainView UI 구현
  Flicker.xcodeproj/project.pbxproj
  Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
  Flicker/Screens/Main/Cell/RegionCollectionViewCell.swift
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: feature, 코비

#18 :lipstick: 로그인 플로우에 맞는 디자인을 구현했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Global/Extensions/UIColor+Extension.swift
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
  Flicker/Screens/SignUp/ProfileSettingViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: feature, 하디

#23 :lipstick: 테이블뷰의 기본 화면을 구성했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UIColor+Extension.swift
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/Profile/AccountDeleteViewController.swift
  Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
  Flicker/Screens/Profile/Cell/ProfileTableViewCell.swift
  Flicker/Screens/Profile/ProfileHeaderVIew.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: feature, 켄

#24 💄 작가 등록 UI 의 반을 구현했습니다. [1]
  Flicker.xcodeproj/project.pbxproj
  Flicker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Flicker/Global/Extensions/UIColor+Extension.swift
  Flicker/Global/Extensions/UILabel+Extension.swift
  Flicker/Global/Resource/Assets.xcassets/AppIcon.appiconset/1024x1024ShuggleLogo.png
  Flicker/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/artistReg1.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/artistReg1.imageset/artistReg1.png
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/ArtistRegister/LeftAlignedCollectionViewFlowLayout.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterEndViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterRegionViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterTextDescriptionViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterWelcomeViewController.swift
  Flicker/Screens/ArtistRegister/Views/RegisterCustomNavigationView.swift
  Flicker/Screens/ArtistRegister/Views/RegisterRegionTagCell.swift
Labels: feature, 피칸파이

#25 ✨ 프로필이미지 설정 기능 추가
  Flicker/Screens/SignUp/LoginProfileViewController.swift
Labels: feature, 하디

#33 ✨깃모지를 레포 곳곳에 추가하였습니다.
  .github/ISSUE_TEMPLATE/Refactoring-Template.yml
  .github/ISSUE_TEMPLATE/feature-issue-template.yml
  .github/ISSUE_TEMPLATE/fix-issue-template.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 하디, 🛠 Chore

#32 🎨 UILabelextension추가 및 적용, lazy var적용을 했습니다 ( + iOS 버젼 14추가)
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UILabel+Extension.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
Labels: 🐛bug, ✨feature, 하디

#35 💄 LoginProfileViewController를 피그마에 맞게 수정했습니다.
  Flicker/Screens/SignUp/LoginProfileViewController.swift
Labels: 하디, 🛠 Chore

#36 작가 등록 UI 및 기능 구현 [2]
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterEndViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterRegionViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterTextDescriptionViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterWelcomeViewController.swift
  Flicker/Screens/ArtistRegister/Views/RegisterAddPhotosCollectionViewCell.swift
  Flicker/Screens/ArtistRegister/Views/RegisterPortfolioImageCell.swift
  Flicker/Screens/ArtistRegister/Views/RegisterRegionTagCell.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: ✨Feat, 피칸파이

#31 💄 메세지 관련 화면과 기능 구현
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/UIComponent/PaddingLabel.swift
  Flicker/Global/UIComponent/SendButton.swift
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Global/Utils/PushNotificationSender.swift
  Flicker/Models/ChatMessage.swift
  Flicker/Models/Message/Channel.swift
  Flicker/Models/Message/ImageMediaItem.swift
  Flicker/Models/Message/Message.swift
  Flicker/Models/Message/Mocks.swift
  Flicker/Models/Message/Sender.swift
  Flicker/Models/RecentMessage.swift
  Flicker/Models/User.swift
  Flicker/Screens/Channels/Cell/ChannelTableViewCell.swift
  Flicker/Screens/Channels/ChannelsViewController.swift
  Flicker/Screens/Chat/Cell/ChatTableViewCell.swift
  Flicker/Screens/Chat/Cell/MyChatTableViewCell.swift
  Flicker/Screens/Chat/ChatViewController.swift
  Flicker/Screens/Chat/UIComponent/ChatSendView.swift
  Flicker/Screens/Message/Cell/MessageTableViewCell.swift
  Flicker/Screens/Message/MessageViewController.swift
  Flicker/Screens/MessageRoom/MessageRoomViewController.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: ✨Feat, 코비

#44 :sparkles: 로그인 실패 시 얼럿을 통한 확인 및 뷰가 로드 될 때 키보드가 뜨는 이슈 제거했습니다.
  Flicker/Screens/Login/LoginViewController.swift
Labels: 하디, 🛠 Chore

#48 💄메인 화면 UI 개선
  Flicker/Global/Literal/ImageLiteral.swift
  Flicker/Global/Resource/Assets.xcassets/logo.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/logo.imageset/logo.png
  Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: 코비, 🛠 Chore

#47 작가 등록 화면의 UI 버그 수정 및 UX 개선을 했습니다.
  Flicker/Global/Resource/Assets.xcassets/gliderWithoutBG.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/gliderWithoutBG.imageset/ShugglePNG.png
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterRegionViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterTextDescriptionViewController.swift
  Flicker/Screens/ArtistRegister/Views/RegisterCustomNavigationView.swift
Labels: 🐛Bug, ✨Feat, 피칸파이

#50 프로필 화면을 수정된 MVP에 맞게 수정하였습니다.
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Global/Resource/Assets.xcassets/DefaultProfile.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/DefaultProfile.imageset/DefaultProfile.png
  Flicker/Screens/Profile/AccountDeleteViewController.swift
  Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
  Flicker/Screens/Profile/Cell/ProfileTableViewCell.swift
  Flicker/Screens/Profile/ProfileHeaderVIew.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 켄

#54 CardView에 네비게이션 기능을 넣었습니다
  Flicker/Screens/Profile/ProfileHeaderVIew.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 켄

#52 💄 ArtisTappedView의 UI를 수정했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Global/Extensions/UITextView+Extension.swift
  Flicker/Network/NetworkErrorCase.swift
  Flicker/Network/NetworkManager.swift
  Flicker/Screens/Artist/ArtistPortfolioCell.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
  Flicker/Screens/Artist/ImageViewController.swift
Labels: ✨Feat, 루키

#57 :lipstick: 다크모드를 미지원으로 고정합니다.
  Flicker/Global/Supports/Info.plist
Labels: 하디, 🛠 Chore

#62 :fire: 둘러보기 기능을 삭제했습니다.
  Flicker/Screens/Login/LoginViewController.swift
Labels: 하디, 🛠 Chore

#71 ⚡ 작가 등록 화면에서 Firebase 업로드 기능 구현 및 속도를 향상 시켰습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Models/Artist.swift
  Flicker/Screens/ArtistRegister/Cell/RegisterAddPhotosCollectionViewCell.swift
  Flicker/Screens/ArtistRegister/Cell/RegisterPortfolioImageCell.swift
  Flicker/Screens/ArtistRegister/Cell/RegisterRegionTagCell.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
Labels: 🐛Bug, ✨Feat, 피칸파이

#68 ✨ 비밀번호 재설정 기능 추가했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/ProfileSetting/InputPassword/InputPasswordViewController.swift
Labels: 🐛Bug, ✨Feat, 하디

#70 🐛 ArtistTappedView UI 및 이미지 로드 관련 버그를 수정했습니다.
  Flicker/Network/NetworkManager.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/ImageViewController.swift
Labels: 🐛Bug, ✨Feat, 루키

#72 로그아웃과 회원탈퇴를 담당하는 셀을 만들었습니다.
  Flicker/Global/Resource/Assets.xcassets/장루키.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/장루키.imageset/장루키.jpeg
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: 켄, 🛠 Chore

#73 ✨ 메인화면 UI/UX 수정하고 및 지역 설정 기능을 추가
  Flicker.xcodeproj/project.pbxproj
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Main/UIComponent/AppTitleView.swift
  Flicker/Screens/Main/UIComponent/RegionTagView.swift
  Flicker/Screens/Region/RegionViewController.swift
Labels: ✨Feat, 코비

#77 프로필뷰에서 네비게이션 바를 지우고 ViewControllerExtension에 네비게이션 관련 함수를 넣었습니다. [#66]
  Flicker/Global/Extensions/UIViewController+Extension.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 켄

#82 ✨ 메인화면에서 지역선택을 복수로 할 수 있도록 기능을 수정하였습니다.
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Region/RegionViewController.swift
  Flicker/Screens/Region/UIComponent/RegionTagListView.swift
Labels: ✨Feat, 코비

#84 🐛 태그버튼 오류 수정
  Flicker/Screens/Main/MainViewController.swift
Labels: 🐛Bug, ✨Feat, 코비, 🚑 Emergency

#87 Fix/80 fix login&with draw
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Profile/AccountDeleteViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/ProfileSetting/InputPassword/InputPasswordViewController.swift
  Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
  Flicker/Screens/WithDraw/WithDrawViewController.swift
Labels: 하디, 🛠 Chore

#91 ✨ 메인화면 스켈레톤 UI 적용
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UIColor+Extension.swift
  Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: ✨Feat, 코비

#88 🎨 곳곳에 흩어져있던 로그인 관련 함수들을 한 곳에 모았습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Global/Utils/AppleLoginManager.swift
  Flicker/Global/Utils/LoginManager.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: 하디, 🛠 Chore

#95 ✨ 컨셉 태그를 추가하는 화면을 작가 등록에 추가했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Models/Artist.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterConceptTagViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterTextDescriptionViewController.swift
Labels: ✨Feat, 피칸파이, 🛠 Chore

#101 🚑 데이터의 네트워킹을 위해 Artist Model 을 Codable 하게 만듭니다.
  Flicker/Models/Artist.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
Labels: 🐛Bug, 피칸파이, 🚑 Emergency

#93 ✨ 프로필뷰에 파이어베이스를 연동했습니다.
  Flicker/Models/User.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Profile/Cell/ProfileTableViewCell.swift
  Flicker/Screens/Profile/ProfileHeaderVIew.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
Labels: ✨Feat, 켄

#98 ✨BaseViewController로 이메일 발송 기능 이관 및 신고 양식 개발
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Utils/EmailViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 켄

#105 ✨ UserDefault에 있는 값을 회원가입 및 로그아웃 할때 삭제하는 코드를 추가했습니다.
  Flicker/Models/User.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 하디

#108 ✨ 작가 정보에 UserDefaults 값을 추가하여 Artist 정보에 추가합니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UserDefaults+Extension.swift
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Models/User.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 피칸파이

#109 💄 🎨 ArtistTappedView 세부 UI 조정 및 스켈레톤 추가
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Global/Extensions/ArrayExtension.swift
  Flicker/Global/Extensions/UITextView+Extension.swift
  Flicker/Global/Supports/Info.plist
  Flicker/Network/APIResponseDTO.swift
  Flicker/Network/AccessKey.swift
  Flicker/Network/NetworkManager.swift
  Flicker/Screens/Artist/ArtistPortfolioCell.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
Labels: ✨Feat, 루키

#112 ✨ 🐛 서버에 중복된 이메일이여도 로그인처리되는 것 처럼 보이는 버그를 해결했습니다.
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
Labels: 🐛Bug, ✨Feat, 하디

#115 ✨🐛💄 프로필세팅뷰의 기능을 붙였습니다.
  Flicker/Models/User.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
Labels: 🐛Bug, ✨Feat, 켄

#117 ✨ ArtistTappedView 작가 정보 데이터 업데이트 기능 추가
  Flicker/Global/Extensions/ArrayExtension.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
Labels: ✨Feat, 루키

#121 🚑 Userdefault에 저장되고 삭제되는 값을 추가했습니다.
  Flicker/Models/User.swift
Labels: 하디, 🚑 Emergency

#119 🐛 회원가입 할때 닉네임 필드 및 작가여부에 관련된 버그로 회원가입이 성공하게 되는 버그 해결 & 애플 로그인 중 닉네임을 입력하는 화면에서 앱을 껏다가 키면 메인화면으로 가게되는 버그를 수정했습니다.
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
Labels: 🐛Bug, ✨Feat, 하디

#124 🚑 네트워킹을 위한 아티스트 데이터에 uid 를 넣었습니다.
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
Labels: 피칸파이, 🚑 Emergency

#126 🚑 Userdefault의 키값 current삭제
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
Labels: 하디, 🚑 Emergency

#127 ✨채팅기능을 연결하였습니다.
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Channels/ChannelsViewController.swift
  Flicker/Screens/Chat/Cell/ChatTableViewCell.swift
  Flicker/Screens/Chat/ChatViewController.swift
Labels: ✨Feat, 코비

#128 ✨검색뷰화면을 만들었습니다. (제안)
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
  Flicker/Screens/Search/Cell/ThumnailCollectionViewCell.swift
  Flicker/Screens/Search/SearchViewController.swift
Labels: ✨Feat, 코비

#134 🐛 아티스트탭뷰를 왔다갔다 할 때 생기는 오류를 수정
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
  Flicker/Screens/Chat/ChatViewController.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: 🐛Bug, 코비

#138 ✨ 세로모드로 고정하도록 설정을 했습니다.
  Flicker/Global/Supports/AppDelegate.swift
Labels: 하디, ⚙️Setting

#137 🐛 🚑 네비게이션 바 관련 버그 & 로그아웃 후 애플로그인 시 프로필입력 창으로 가는 버그 & 로그아웃 후 애플로그인할시 Userdefault에 저장하지 않던 오류 수정
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: 🐛Bug, 하디, 🛠 Chore

#139 🐛 iOS 최소 지원버전에 맞게 모달을 커스텀했습니다.
  Flicker/Global/UIComponent/PresentationController.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: ✨Feat, 코비, 🛠 Chore

#141 🐛 하프 모달 파일 해결
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/UIComponent/PresentationController.swift
Labels: 🐛Bug, 코비, 🚑 Emergency

#144 🐛 ArtisTappedView(= 작가디테일뷰) 네비게이션바 관련 버그 수정
  Flicker/Screens/Artist/ArtistPortfolioCell.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: 🐛Bug, 루키

#146 🐛 메인화면 무한 스크롤 에러 해결
  Flicker/Screens/Main/MainViewController.swift
Labels: 🐛Bug, 코비

#151 💄 헤더뷰 안의 이메일을 삭제하고 아이디의 설정을 바꿨습니다. + 헤더뷰 위치 재조정되는 버그를 수정했습니다.
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Profile/ProfileHeaderVIew.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 켄, 루키

#152 🎨 메인화면 관련 코드 전면 수정
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Models/Artist.swift
  Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Region/RegionViewController.swift
Labels: 🐛Bug, ✨Feat, 코비, 🛠 Chore

#155 ✨ 프로필뷰 알림 설정 버튼 활성화
  Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 코비, 🛠 Chore, ⚙️Setting

#154 ✨ ArtistTappedViwe(작가 디테일뷰)와 ChattinngView에서 신고하기 기능이 추가되었습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Extensions/UIViewController+Extension.swift
  Flicker/Global/Literal/ImageLiteral.swift
  Flicker/Global/UIComponent/ReportButton.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Chat/ChatViewController.swift
Labels: ✨Feat, 루키

#159 🐛 💄 회원가입 화면에서 메인화면으로 넘어갈때 버튼이 여러번 클릭 되는 버그를 해결했습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: 🐛Bug, 하디, ⚙️Setting

#163 ✨ 회원가입시 닉네임의 길이를 8글자로 제한하는 기능을 추가했습니다.
  Flicker/Screens/SignUp/LoginProfileViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
Labels: ✨Feat, 하디

#165 💄 프로필 세팅 뷰에 있던 프로필 테이블뷰의 헤더가 올라가던 버그를 해결했습니다.
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Main/MainViewController.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: 🐛Bug, 하디, 루키, 🛠 Chore

#166 🐛 ProfileSetting에서 이동이 가능하게 만들었고 버튼을 눌렀을때 돌아가는 곳을 Profile로 수정했습니다.
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
  Flicker/Screens/Tabbar/TabbarViewController.swift
Labels: 🐛Bug, 켄

#169 🎨 메인화면 작가 썸네일 셀 비율 수정
  Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: 코비, 🛠 Chore

#171 :bug: ArtistTappedView의 네비게이션바 관련 버그 수정
  Flicker/Screens/Main/MainViewController.swift
Labels: 🐛Bug, 루키

#177 💄 기기의 너비,높이 값 Static으로 추가 & 기기별 대응하도록 UI수정
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Utils/Static.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
  Flicker/Screens/Profile/ProfileHeaderVIew.swift
  Flicker/Screens/Profile/ProfileViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
  Flicker/Screens/WithDraw/WithDrawViewController.swift
Labels: 하디, 🛠 Chore

#179 ✨ 작가의 정보 중 포트폴리오(이미지) 를 수정할 수 있습니다.
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Supports/SceneDelegate.swift
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Models/EditData.swift
  Flicker/Models/User.swift
  Flicker/Screens/ArtistEdit/Cell/ArtistEditItemsTableViewCell.swift
  Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditDescriptionViewController.swift
  Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditGearsViewController.swift
  Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditPortfoiloViewController.swift
  Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditRegionsViewController.swift
  Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditTagsViewController.swift
  Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterConceptTagViewController.swift
  Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
  Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
  Flicker/Screens/Profile/ProfileViewController.swift
Labels: ✨Feat, 피칸파이
