Repository DeveloperAcademy-POSTECH/MacC-Dime-Flicker, pull requests merged in 2022-12, with the labels that each got.

#187 📝 Update README.md
  README.md
Labels: 코비

#188 📝 Update README.md
  README.md
Labels: 코비

#184 ✨이메일이 동작하게 수정했습니다.
  Flicker/Global/Utils/EmailViewController.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Chat/ChatViewController.swift
Labels: 켄, 🛠 Chore

#186 💄 회원가입 플로우에 뒤로가기 버튼 추가 및 스와이프 제스쳐 기능 추가
  Flicker/Global/Base/BaseViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
  Flicker/Screens/SignUp/SignUpViewController.swift
Labels: 하디, 🛠 Chore

#193 💄 PopUpViewcontroller의 UI를 수정사항에 맞게 수정하여 반영하였습니다.
  Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
Labels: 하디, 🛠 Chore

#194 ✨ 🐛 ArtistTappedView관련 버그 수정 + 이미지 스와이프 및 확대 축소 기능 추가
  Flicker.xcodeproj/project.pbxproj
  Flicker/Global/Resource/Assets.xcassets/artistReg1.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/artistReg1.imageset/artistReg1 복사본.png
  Flicker/Global/Resource/Assets.xcassets/port1.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port1.imageset/IMG_8377.jpg
  Flicker/Global/Resource/Assets.xcassets/port2.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port2.imageset/IMG_8378.jpg
  Flicker/Global/Resource/Assets.xcassets/port3.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port3.imageset/IMG_8379.jpg
  Flicker/Global/Resource/Assets.xcassets/port4.imageset/Contents.json
  Flicker/Global/Resource/Assets.xcassets/port4.imageset/IMG_8380.jpg
  Flicker/Network/NetworkManager.swift
  Flicker/Screens/Artist/ArtistPortfolioCell.swift
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/HeaderCollectionReusableView.swift
  Flicker/Screens/Artist/ImageSliderViewController.swift
  Flicker/Screens/Artist/ImageViewController.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: 🐛Bug, ✨Feat, 루키

#197 🐛 작가등록 후 로그아웃시 작가등록 여부 값을 저장하는 코드를 추가했습니다.
  Flicker/Global/Utils/FirebaseManager.swift
  Flicker/Models/User.swift
  Flicker/Screens/Login/LoginViewController.swift
  Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
  Flicker/Screens/SignUp/LoginProfileViewController.swift
Labels: 하디, 🚑 Emergency

#199 🐛 지역 태그 10개 넘을시, 처음꺼 삭제
  Flicker/Screens/Region/RegionViewController.swift
  Flicker/Screens/Region/UIComponent/RegionTagListView.swift
Labels: 🐛Bug, 코비

#200 🐛 채팅시에 키보드 Hide 범위 수정
  Flicker/Screens/Chat/ChatViewController.swift
Labels: 🐛Bug, 코비, 🛠 Chore

#203 💄 작가 포트폴리오 이미지 전체화면 취소 버튼 UI 변경 및 작가디테일뷰 스와이프해서 뒤로가기 추가
  Flicker/Screens/Artist/ArtistTappedViewController.swift
  Flicker/Screens/Artist/ImageSliderViewController.swift
  Flicker/Screens/Main/MainViewController.swift
Labels: ✨Feat, 루키

#207 :bug: 회원가입 시 발생되는 버그 해결
  Flicker/Screens/SignUp/LoginProfileViewController.swift
Labels: 🐛Bug, 하디, 🚑 Emergency
